/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul.pkg9;

/**
 *
 * @author W8
 */
public class Array extends javax.swing.JFrame {

    /**
     * Creates new form Array
     */
    public Array() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Alamat = new javax.swing.JTextField();
        Waktu = new javax.swing.JTextField();
        JenisKelamin = new javax.swing.JTextField();
        Kewar = new javax.swing.JTextField();
        Golongan = new javax.swing.JTextField();
        Spesialis = new javax.swing.JTextField();
        Status = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        Usia = new javax.swing.JTextField();
        pilihdokter = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Waktu Praktek");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 390, 100, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pemilihan Dokter");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(146, 19, 200, 30);

        jLabel3.setText("Pilih Dokter");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 60, 80, 20);

        jLabel5.setText("Nama");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 110, 80, 20);

        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 150, 80, 20);

        jLabel7.setText("Usia");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 190, 80, 20);

        jLabel8.setText("Jenis Kelamin");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 230, 80, 20);

        jLabel9.setText("Golongan darah");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 280, 80, 14);

        jLabel10.setText("Status");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 320, 80, 20);

        jLabel11.setText("Dokter Spesialis");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 440, 100, 20);

        jLabel12.setText("Kewarganegaraan");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(60, 350, 100, 20);

        Alamat.setEditable(false);
        Alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlamatActionPerformed(evt);
            }
        });
        getContentPane().add(Alamat);
        Alamat.setBounds(170, 150, 170, 30);

        Waktu.setEditable(false);
        getContentPane().add(Waktu);
        Waktu.setBounds(170, 390, 170, 30);

        JenisKelamin.setEditable(false);
        JenisKelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JenisKelaminActionPerformed(evt);
            }
        });
        getContentPane().add(JenisKelamin);
        JenisKelamin.setBounds(170, 230, 170, 30);

        Kewar.setEditable(false);
        Kewar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KewarActionPerformed(evt);
            }
        });
        getContentPane().add(Kewar);
        Kewar.setBounds(170, 350, 170, 30);

        Golongan.setEditable(false);
        Golongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GolonganActionPerformed(evt);
            }
        });
        getContentPane().add(Golongan);
        Golongan.setBounds(170, 270, 170, 30);

        Spesialis.setEditable(false);
        Spesialis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpesialisActionPerformed(evt);
            }
        });
        getContentPane().add(Spesialis);
        Spesialis.setBounds(170, 430, 170, 30);

        Status.setEditable(false);
        Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusActionPerformed(evt);
            }
        });
        getContentPane().add(Status);
        Status.setBounds(170, 310, 170, 30);

        Nama.setEditable(false);
        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        getContentPane().add(Nama);
        Nama.setBounds(170, 110, 170, 30);

        Usia.setEditable(false);
        Usia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsiaActionPerformed(evt);
            }
        });
        getContentPane().add(Usia);
        Usia.setBounds(170, 190, 170, 30);

        pilihdokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr. Lala", "Dr. Ayun", "Dr. Dino" }));
        pilihdokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihdokterActionPerformed(evt);
            }
        });
        getContentPane().add(pilihdokter);
        pilihdokter.setBounds(140, 60, 170, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas"));
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 90, 550, 390);

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 550, 90);

        setBounds(0, 0, 559, 517);
    }// </editor-fold>//GEN-END:initComponents

    private void AlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatActionPerformed

    private void SpesialisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpesialisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpesialisActionPerformed

    private void StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusActionPerformed

    private void GolonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GolonganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GolonganActionPerformed

    private void JenisKelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JenisKelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JenisKelaminActionPerformed

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void UsiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsiaActionPerformed

    private void pilihdokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihdokterActionPerformed
        // TODO add your handling code here:
        if(pilihdokter.getSelectedItem().equals("Dr. Lala")) {
        Nama.setText("Dr. Lala");
        Alamat.setText("Jln. Surabaya 16, Malang");
        Usia.setText("21 tahun");
        JenisKelamin.setText("Perempuan");
        Golongan.setText("B");
        Status.setText("Belum Menikah");
        Kewar.setText("Indonesia");
        Waktu.setText("Siang (11.00 - 12.00)");
        Spesialis.setText("Bedah");
        }
        else
            if(pilihdokter.getSelectedItem().equals("Dr. Ayun")){
            Nama.setText("Dr. Ayun");
            Alamat.setText("Jl. Pancasila No 1, Malang");
            Usia.setText("20 Tahun");
            JenisKelamin.setText("Perempuan");
            Golongan.setText("O");
            Status.setText("Beum Menikah");
            Kewar.setText("Indonesia");
            Spesialis.setText("Dokter Gigi");
            Waktu.setText("Pagi (08.00-09.00)");
            }
        else
if(pilihdokter.getSelectedItem().equals("Dr. Dino")){
Nama.setText("Dr. Dino");
Alamat.setText("Jl. Bandung 9, Malang");
Usia.setText("20 Tahun");
JenisKelamin.setText("Laki-Laki");
Golongan.setText("B");
Status.setText("Belum Menikah");
Kewar.setText("Indonesia");
Spesialis.setText("Dokter Gizi");
Waktu.setText(" Malam (22.00-06.00)");
}
    }//GEN-LAST:event_pilihdokterActionPerformed

    private void KewarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KewarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KewarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Array.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Array.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Array.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Array.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Array().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alamat;
    private javax.swing.JTextField Golongan;
    private javax.swing.JTextField JenisKelamin;
    private javax.swing.JTextField Kewar;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Spesialis;
    private javax.swing.JTextField Status;
    private javax.swing.JTextField Usia;
    private javax.swing.JTextField Waktu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> pilihdokter;
    // End of variables declaration//GEN-END:variables
}
